### ISSUE TITLE
User "shutup" input responds with canned error message for UNKNOWN_ERROR.

### ISSUE THREAD

**Issue by gootla-manasa** [s-maheshbabu/silent-alexa#40]
User: shutup
Alexa: a canned response for UNKNOWN_ERROR. This shouldn't ever happen. Don't show it as an Alexa bubble.

This is happening because Alexa's response has empty payload.

**Comment by s-maheshbabu** [comment]
I think this will be fixed by https://github.com/s-maheshbabu/silent-alexa/issues/22

**Comment by s-maheshbabu** [comment]
Sometimes Alexa can respond with absolutely nothing at all (like in response to shut up). This is different from Alexa responding with an empty message (like in response to shutup).

Not sure why they draw this distinction but we need to handle empty payloads.

**Comment by s-maheshbabu** [comment]
Assigned to @gootla-manasa to verify and resolve.

**Comment by gootla-manasa** [comment]
Ship it!
